//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PwaPSiWrapper2.Layouts.PwaPSiWrapper2 {
    
    
    public partial class PwaAdapter {
    }
}
